"""
SHIELD-generated: regional order aggregation with sanity checks
Auto-generated by SHIELD Pipeline Generation Agent.
"""
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.operators.python import PythonOperator

DAG_ID = "shield_generated_regional_orders"
POSTGRES_CONN_ID = "shield_postgres"
ROW_COUNT_DELTA_THRESHOLD_PCT = 20

SQL_QUERY = """SELECT c.c_nationkey AS nation_key,
               SUM(o.o_totalprice) AS total_order_value,
               COUNT(o.o_orderkey) AS order_count
        FROM tpch.orders o
        JOIN tpch.customer c ON o.o_custkey = c.c_custkey
        GROUP BY c.c_nationkey
        ORDER BY nation_key;"""

TARGET_SETUP_SQL = """CREATE TABLE IF NOT EXISTS analytics.regional_orders_shield (nation_key INTEGER NOT NULL, total_order_value DECIMAL NOT NULL, order_count BIGINT NOT NULL, run_timestamp TIMESTAMP DEFAULT now());
TRUNCATE TABLE analytics.regional_orders_shield;"""

INSERT_SQL_TEMPLATE = """INSERT INTO analytics.regional_orders_shield (nation_key, total_order_value, order_count) VALUES (%s, %s, %s);"""


def extract_and_check(**context):
    hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
    hook.run(TARGET_SETUP_SQL)

    records = hook.get_records(SQL_QUERY)
    original_count = len(records)

    if original_count == 0:
        raise ValueError("No records returned -- source query produced empty result.")

    context["ti"].xcom_push(key="original_count", value=original_count)
    context["ti"].xcom_push(key="records", value=records)
    print(f"Extracted {original_count} rows.")


def load_with_sanity_check(**context):
    ti = context["ti"]
    records = ti.xcom_pull(key="records", task_ids="extract_and_check")
    original_count = ti.xcom_pull(key="original_count", task_ids="extract_and_check")

    final_count = len(records)
    delta_pct = abs(original_count - final_count) / original_count * 100 if original_count else 0

    if delta_pct > ROW_COUNT_DELTA_THRESHOLD_PCT:
        raise ValueError(
            f"SANITY CHECK FAILED: row count changed by {delta_pct:.1f}% "
            f"(original={original_count}, final={final_count}), "
            f"exceeding threshold of {ROW_COUNT_DELTA_THRESHOLD_PCT}%. "
            f"Halting to prevent silent data loss -- escalating per Step 9 healing policy."
        )

    # Deterministic column-count validation gate (Step 15 finding). Do not
    # trust the LLM-generated INSERT template's placeholder count blindly --
    # verify it matches the actual extracted row shape before executing, and
    # fail with a clear, diagnostic error rather than an opaque IndexError.
    placeholder_count = INSERT_SQL_TEMPLATE.count("%s")
    actual_col_count = len(records[0]) if records else 0
    if placeholder_count != actual_col_count:
        raise ValueError(
            f"SCHEMA MISMATCH: INSERT template expects {placeholder_count} values "
            f"but extracted rows have {actual_col_count} columns. "
            f"Likely a Pipeline Generation Agent DDL/INSERT mismatch -- escalating "
            f"rather than attempting a partial/misaligned insert."
        )

    hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
    conn = hook.get_conn()
    cursor = conn.cursor()
    for row in records:
        cursor.execute(INSERT_SQL_TEMPLATE, row)
    conn.commit()
    cursor.close()
    conn.close()

    print(f"Loaded {final_count} rows (delta: {delta_pct:.1f}%, within threshold).")


default_args = {
    "owner": "shield-project",
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id=DAG_ID,
    description="SHIELD-generated: regional order aggregation with sanity checks",
    default_args=default_args,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["shield", "generated"],
) as dag:

    extract_task = PythonOperator(
        task_id="extract_and_check",
        python_callable=extract_and_check,
    )

    load_task = PythonOperator(
        task_id="load_with_sanity_check",
        python_callable=load_with_sanity_check,
    )

    extract_task >> load_task
