"""
SHIELD Agent 4: Pipeline Generation Agent
Per Step 10 spec: wraps SQL (Agent 2) + transformation rules (Agent 3) into
an Airflow DAG. Uses a Hybrid template + LLM fill-in approach (per Prompt2DAG's
finding that Hybrid outperforms LLM-only DAG generation), not pure LLM generation.

Includes an explicit row-count-delta sanity gate, motivated directly by the
Step 14 (composite-FK) and Step 15 (semantically-blind null-handling) findings:
execution/transformation success alone is not sufficient evidence of a
correct outcome.

Also includes a deterministic column-count validation gate (Step 15 finding):
the LLM initially generated an INSERT template with a mismatched placeholder
count (4 placeholders including run_timestamp, vs. 3 actual extracted
columns), causing a runtime IndexError. Fixed via (1) a more explicit prompt
instructing the LLM not to include run_timestamp in the INSERT, and (2) a
deterministic runtime check in the generated DAG that fails loudly with a
diagnostic SCHEMA MISMATCH error if the LLM still gets it wrong, rather than
an opaque IndexError.
"""
import json
import re
import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "qwen2.5:14b"

ROW_COUNT_DELTA_THRESHOLD_PCT = 20  # flag if transformation changes row count by more than this %

DAG_TEMPLATE = '''"""
{dag_description}
Auto-generated by SHIELD Pipeline Generation Agent.
"""
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.operators.python import PythonOperator

DAG_ID = "{dag_id}"
POSTGRES_CONN_ID = "shield_postgres"
ROW_COUNT_DELTA_THRESHOLD_PCT = {threshold}

SQL_QUERY = """{sql_query}"""

TARGET_SETUP_SQL = """{target_setup_sql}"""

INSERT_SQL_TEMPLATE = """{insert_sql_template}"""


def extract_and_check(**context):
    hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
    hook.run(TARGET_SETUP_SQL)

    records = hook.get_records(SQL_QUERY)
    original_count = len(records)

    if original_count == 0:
        raise ValueError("No records returned -- source query produced empty result.")

    context["ti"].xcom_push(key="original_count", value=original_count)
    context["ti"].xcom_push(key="records", value=records)
    print(f"Extracted {{original_count}} rows.")


def load_with_sanity_check(**context):
    ti = context["ti"]
    records = ti.xcom_pull(key="records", task_ids="extract_and_check")
    original_count = ti.xcom_pull(key="original_count", task_ids="extract_and_check")

    final_count = len(records)
    delta_pct = abs(original_count - final_count) / original_count * 100 if original_count else 0

    if delta_pct > ROW_COUNT_DELTA_THRESHOLD_PCT:
        raise ValueError(
            f"SANITY CHECK FAILED: row count changed by {{delta_pct:.1f}}% "
            f"(original={{original_count}}, final={{final_count}}), "
            f"exceeding threshold of {{ROW_COUNT_DELTA_THRESHOLD_PCT}}%. "
            f"Halting to prevent silent data loss -- escalating per Step 9 healing policy."
        )

    # Deterministic column-count validation gate (Step 15 finding). Do not
    # trust the LLM-generated INSERT template's placeholder count blindly --
    # verify it matches the actual extracted row shape before executing, and
    # fail with a clear, diagnostic error rather than an opaque IndexError.
    placeholder_count = INSERT_SQL_TEMPLATE.count("%s")
    actual_col_count = len(records[0]) if records else 0
    if placeholder_count != actual_col_count:
        raise ValueError(
            f"SCHEMA MISMATCH: INSERT template expects {{placeholder_count}} values "
            f"but extracted rows have {{actual_col_count}} columns. "
            f"Likely a Pipeline Generation Agent DDL/INSERT mismatch -- escalating "
            f"rather than attempting a partial/misaligned insert."
        )

    hook = PostgresHook(postgres_conn_id=POSTGRES_CONN_ID)
    conn = hook.get_conn()
    cursor = conn.cursor()
    for row in records:
        cursor.execute(INSERT_SQL_TEMPLATE, row)
    conn.commit()
    cursor.close()
    conn.close()

    print(f"Loaded {{final_count}} rows (delta: {{delta_pct:.1f}}%, within threshold).")


default_args = {{
    "owner": "shield-project",
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
}}

with DAG(
    dag_id=DAG_ID,
    description="{dag_description}",
    default_args=default_args,
    schedule=None,
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["shield", "generated"],
) as dag:

    extract_task = PythonOperator(
        task_id="extract_and_check",
        python_callable=extract_and_check,
    )

    load_task = PythonOperator(
        task_id="load_with_sanity_check",
        python_callable=load_with_sanity_check,
    )

    extract_task >> load_task
'''


def call_llm(prompt: str, max_retries: int = 3, retry_delay: float = 5.0) -> str:
    import time
    last_error = None
    for attempt in range(1, max_retries + 1):
        try:
            response = requests.post(
                OLLAMA_URL,
                json={"model": MODEL, "prompt": prompt, "stream": False, "options": {"temperature": 0.1}},
                timeout=180,
            )
            response.raise_for_status()
            return response.json()["response"]
        except (requests.exceptions.ConnectionError, requests.exceptions.RequestException) as e:
            last_error = e
            if attempt < max_retries:
                time.sleep(retry_delay)
    raise ConnectionError(f"Ollama call failed after {max_retries} attempts: {last_error}")


def llm_fill_target_schema(sql_query: str, target_table: str, target_schema: str = "analytics") -> dict:
    """
    LLM role (scoped, per Prompt2DAG's Hybrid finding -- LLM fills in specific
    slots within a fixed template, not free-form DAG generation).
    Infers target table structure from the source query's SELECT columns.
    """
    prompt = f"""Given this SQL query:
{sql_query}

Generate PostgreSQL DDL for a target table named "{target_schema}.{target_table}"
that matches the query's output columns EXACTLY (infer reasonable types from column names/aliases).
Include a run_timestamp TIMESTAMP DEFAULT now() column in the CREATE TABLE statement ONLY.

Do NOT include run_timestamp in the INSERT statement's column list or VALUES clause --
it will be set automatically by the table's DEFAULT now(). The INSERT statement must have
EXACTLY as many %s placeholders as there are columns in the source query's SELECT clause,
no more, no fewer.

Also generate the matching TRUNCATE statement.

Output ONLY valid JSON with three keys: "create_table_sql", "truncate_sql", "insert_sql".
No explanation, no markdown fences."""

    output = call_llm(prompt)
    match = re.search(r"\{.*\}", output, re.DOTALL)
    if match:
        try:
            target_defs = json.loads(match.group(0))
            # Enforce idempotency deterministically -- do not rely on the LLM
            # to remember IF NOT EXISTS every time (Step 15 finding: generated
            # DDL failed on concurrent/repeated runs with DuplicateTable error).
            target_defs["create_table_sql"] = re.sub(
                r"CREATE TABLE\s+(?!IF NOT EXISTS)",
                "CREATE TABLE IF NOT EXISTS ",
                target_defs["create_table_sql"],
                flags=re.IGNORECASE,
            )
            return target_defs
        except json.JSONDecodeError:
            pass
    raise ValueError(f"LLM did not return valid JSON for target schema: {output[:300]}")


def generate_dag(dag_id: str, dag_description: str, sql_query: str, target_table: str, target_schema: str = "analytics") -> str:
    """
    Main entry point. Hybrid generation: fixed Python/Airflow template (structure,
    control flow, sanity-check gate, and column-count validation gate all
    hardcoded/deterministic), LLM only fills the target-table DDL/INSERT slots.
    """
    target_defs = llm_fill_target_schema(sql_query, target_table, target_schema)

    dag_code = DAG_TEMPLATE.format(
        dag_id=dag_id,
        dag_description=dag_description,
        threshold=ROW_COUNT_DELTA_THRESHOLD_PCT,
        sql_query=sql_query.strip(),
        target_setup_sql=(
            target_defs["create_table_sql"].strip() + "\n" + target_defs["truncate_sql"].strip()
        ),
        insert_sql_template=target_defs["insert_sql"].strip(),
    )

    return dag_code


if __name__ == "__main__":
    sql = """
        SELECT c.c_nationkey AS nation_key,
               SUM(o.o_totalprice) AS total_order_value,
               COUNT(o.o_orderkey) AS order_count
        FROM tpch.orders o
        JOIN tpch.customer c ON o.o_custkey = c.c_custkey
        GROUP BY c.c_nationkey
        ORDER BY nation_key;
    """
    dag_code = generate_dag(
        dag_id="shield_generated_regional_orders",
        dag_description="SHIELD-generated: regional order aggregation with sanity checks",
        sql_query=sql,
        target_table="regional_orders_shield",
    )

    output_path = "/home/rit/Documents/Shrilaxmi/Data_Engg/infra/airflow/dags/shield_generated_regional_orders.py"
    with open(output_path, "w") as f:
        f.write(dag_code)

    print(f"DAG written to {output_path}")
    print("\n--- Generated DAG ---\n")
    print(dag_code)
